### ISSUE TITLE
Create a homepage banner slider of highlighted repositories

### ISSUE THREAD

**Issue by adamjarling** [samvera/samvera.org#117]
On the Samvera.org homepage, we could add a Hero Banner which acts as a slider which features highlighted Samvera Repository Solutions.

@heathergreerklein Which should these be?   Guessing:

- Hyku
- Hyrax
- Avalon
- Others?  Perhaps lighter-weight, JavaScript IIIF driven component repos such as:
  - https://samvera-labs.github.io/clover-iiif/
  - https://samvera.github.io/serverless-iiif/

I'm biased on the last 2 as I'm an active developer on their teams, however the repositories are tucked under the Samvera banner and could showcase that Samvera is inclusive of all technology solutions, in addition to large, Ruby/Rails monolithic apps?

**Comment by heathergreerklein** [comment]
@adamjarling I definitely support including the component repos!

**Comment by adamjarling** [comment]
Logos sent over my Heather...

Screenshots coming for 
 - Avalon
 - Hyrax
 - Hyku
 - Clover Viewer

**Comment by DraxIndustries79** [comment]
Some Hyku Examples.
![Samvera Repo Screenshot - Hyku](https://github.com/samvera/samvera.org/assets/37004183/c91aea21-bd53-4b93-be65-1116ed8cb8ee)
![BL Screenshot - Hyku](https://github.com/samvera/samvera.org/assets/37004183/298c7a9b-d5bd-4019-8978-aec9b5a2e525)
![U of L Screenshot - Hyku](https://github.com/samvera/samvera.org/assets/37004183/e53e7b1a-5899-4409-aa7a-07a11db8707e)
