### ISSUE TITLE
Populate Samvera Partner data into Contentful CMS

### ISSUE THREAD

**Issue by adamjarling** [samvera/samvera.org#119]
We can now add Samvera Partners data into our Contentful Headless CMS.   The Content Model is already set up, and data is ready to be added...

![image](https://github.com/samvera/samvera.org/assets/3020266/69f62a18-5da8-48e2-8b4d-29acc9c529c7)

## Done looks like
- [x] @heathergreerklein adds Partner info and logos to Contentful CMS
- [x] @adamjarling sets up a new "Parter" component in the application, which will display partners in a modern, "logo cloud" UI pulled from TailwindUI component.

**Comment by heathergreerklein** [comment]
Adam, I added URLs and Partner names, but not logos yet as I need to make sure we have permission to use them. But is there a way to populate the content to the bottom of the current homepage, to populate the partner list?

**Comment by adamjarling** [comment]
@heathergreerklein This looks great!  Yes, we can sync up this data w/o the logo, no problems from what I can initially see in Contentful.  I'll get this (and the other Samvera work) tackled tomorrow and/or Monday.
