### ISSUE TITLE
Architecture ideas for Samvera websites

### ISSUE THREAD

**Issue by adamjarling** [samvera/samvera.org#131]
One idea is to move towards a common solution for how Hyrax, Hyku, and Avalon websites are built.  Currently there are three different solutions for the mentioned sites (Jekyl, WordPress, etc).

- Could this be a static NextJS site build (similar to Samvera.org)?   
- Can we share components? 
- How to handle theming?
- How to make the architecture more inclusive, and not tethered to a single developer (risk management, or identifying what tools Samvera really wants to highlight?

**Comment by heathergreerklein** [comment]
A working group put together a preliminary sitemap that could be relevant to the other platforms as well (under "[what is important to Hyku?](https://docs.google.com/spreadsheets/d/1bvxLStnDtpRg2uKNPkK5CpIxjJcN5S4qvgZULjdKjbQ/edit?usp=sharing)").

**Comment by adamjarling** [comment]
@heathergreerklein 

<img width="1994" alt="Samvera_Family_Website_Architecture_Idea_#1" src="https://github.com/samvera/samvera.org/assets/3020266/e0f5ad09-7551-4c0e-9c4f-2dccc381cd5d">

**Comment by adamjarling** [comment]
### Diagram summary
This approach to combining Samvera organization sites puts a headless CMS (Contentful) at the core of providing data for different websites (samvera.org, Hyku, Hyrax, Avalon).   There would be credentials for maintainers of the sites set up in Contentful, and each application's data would be updatable via Contentful, and pass through to the respective website.

A shared generic template would be set up for each site.  If we run with the current model for Samvera.org, this could be a NextJS site, which creates a static site which is hosted directly within it's Github repository via Github Pages.   

The following, separate Samvera repositories would exist:
- Generic template repository
- Shared React components repository
- Samvera.org repository (exists)
- Avalon promo site repository (new)
- Hyku promo site repository (new)
- Hyrax promo site repository (new)

Some data would be shared across templates (maybe News Items, Navigation, etc).  And some data would be unique to each website.  The idea is it model this information structure within Contentful, and then represent it in the UI for each website.
