### ISSUE TITLE
Administrator instructions for menus

### ISSUE THREAD

**Issue by heathergreerklein** [samvera/samvera.org#20]
As an admin I'd like the documentation to include instructions for:

- Reordering topline menus
- moving a page from one menu item to another (one markdown folder to another)
-

**Comment by adamjarling** [comment]
@heathergreerklein So for the first item, reordering top line menus, this might be tricky.  It's currently set up to just read the directory structure, and it appears to handle things alphabetically.  I'll give it some thought on how we might make this a little easier for Administrators to control.  Possibly through a `.yaml` file?

For moving a page from one nav column to another, you could do so like this:
1. Move the file in the `/markdown` directory to it's new folder.
2. Submit a Pull Request

When the site builds in Github Actions the page will appear in it's new spot.
