### ISSUE TITLE
Create new page: contact us

### ISSUE THREAD

**Issue by heathergreerklein** [samvera/samvera.org#54]
Create a new "contact us" page using Tailwind CSS about page template, "simple with brand contact panel."

This page can replace the page currently located at https://samvera.org/contact-us

**Comment by adamjarling** [comment]
@heathergreerklein Can you point me directly to the Tailwind UI url referenced above?  They might have updated their components recently...

**Comment by heathergreerklein** [comment]
Thanks Adam, I'm not set on a form -- we can stick with what we have for now. Thanks for looking into it!
