### ISSUE TITLE
New page: Community Leadership

### ISSUE THREAD

**Issue by heathergreerklein** [samvera/samvera.org#56]
Create a Community Leadership page using Tailwind CSS team section template "[image with short paragraph](https://tailwindui.com/components/marketing/sections/team-sections#component-0efa5ebc92e2aa72bc2332fcf5578869)." 

This page can list generalized information about the Board, Roadmaps Alignment Group, Product Leadership, Interest/Working Groups, and contact info for the community manager.

This page can replace the existing governance page, and link to the wiki for governance structure details.

**Comment by adamjarling** [comment]
@heathergreerklein Also, I'm going to leave the Governance page in there for now.  Maybe you'll want to copy some content over?  When you're ready to remove it, you can remove the file from the `/markdown/about/...` directory.  Or I can do it if you prefer.
