### ISSUE TITLE
Create a Hyku subdomain template 

### ISSUE THREAD

**Issue by heathergreerklein** [samvera/samvera.org#59]
Create a new subdomain site for Hyku, based on the structure of https://www.avalonmediasystem.org/ . The site could use the same topline menu and pages, but with the Hyku logo and colors.

This would be a site that Hyku leadership can fill in with Hyku-specific information, that can eventually be set as the destination for hyku.samvera.org

**Comment by DraxIndustries79** [comment]
We need to explore what Avalon is using, get aligned with Avalon and Hyrax on a common user-friendly template.
