### ISSUE TITLE
Change top section of homepage to Samvera Connect 2023 promotion

### ISSUE THREAD

**Issue by heathergreerklein** [samvera/samvera.org#93]
This is the easiest approach I've thought of but open to other ideas!

1. Change the top left section (A vibrant and welcoming community...etc) to read:

 ### Join us for Samvera Connect 2023
 October 23rd - 26th in Philadelphia
[See full details on the Samvera wiki](https://samvera.atlassian.net/wiki/spaces/samvera/pages/2174877699/Samvera+Connect+2023)

2. Change existing buttons to:

[Register now](https://samveraconnect2023.sched.com/signup)     

[See the full schedule](https://samveraconnect2023.sched.com)

**Comment by heathergreerklein** [comment]
Optionally can add this image to replace the photo

![2023 philadelpia (1024 × 1024 px) (3)](https://github.com/samvera/samvera.org/assets/18666655/770f595a-afb7-4c5d-956b-57229bdb76ce)

**Comment by adamjarling** [comment]
Gotcha.  Updating now.
